### ISSUE TITLE
source activate -> conda activate

### ISSUE THREAD

**Issue by gtfierro** [jleyden/building-analysis#6]
The README states to run `source activate mortar` to start the environment shell, but I think the command is `conda activate mortar`. Would be good to know if there's a different environment shell I'm missing, though

**Comment by anandkp92** [comment]
I believe John is right: it is `source activate mortar` (https://conda.io/docs/user-guide/tasks/manage-environments.html)

**Comment by jleyden** [comment]
I think `conda activate mortar` is faster and works across operating systems https://stackoverflow.com/questions/49600611/python-anaconda-should-i-use-conda-activate-or-source-activate-in-linux

**Comment by gtfierro** [comment]
Good to know! `source activate` wasn't working for me

**Comment by anandkp92** [comment]
I learned something new! Thank You!

**Comment by jleyden** [comment]
Fixed 
https://github.com/jleyden/building-analysis/pull/8/commits/ddf307613d34b7359ad9058c82abcf79369f30d7

**Comment by jleyden** [comment]
Yikes, `conda activate` only works on PC.
