### ISSUE TITLE
Configuration should use Brick query, not explicit values

### ISSUE THREAD

**Issue by gtfierro** [jleyden/building-analysis#7]
Dispatch the below Brick query against the endpoint we've been using (send me an email if you don't have it) to bootstrap the configuration of where the meter streams are (there are sometimes multiple per site!) 

```sparql
SELECT ?gbm ?uuid FROM sitename WHERE {
    ?gbm rdf:type brick:Green_Button_Meter .
    ?gbm bf:uuid ?uuid
};
```

**Comment by jleyden** [comment]
done https://github.com/jleyden/building-analysis/commit/4162ea84605548418854871cf3a35b8401525736
